title: LegalHub
description: A resource hub for all things legal on Ranch
theme: just-the-docs
logo: "/assets/images/DOJLOGO.png"
 
url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
