title: Ranch LegalHub
description: A resource hub for all things legal on Ranch
theme: just-the-docs
color_scheme: dark

# Correcting the URL to use a single entry
url: https://ABSORO.github.io/LegalHub

collections:
  docs:
    output: true
    permalink: /:path/
    nav_exclude: false

aux_links:
  Community Discord: https://discord.com/invite/Sc3Ur4Uxpp

# Enable search with correct spacing
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
