title: Ranch LegalHub
description: A resource hub for all things legal on Ranch
theme: just-the-docs

 
url: https://just-the-docs.github.io


aux_links:
  Community Discord: https://discord.com/invite/Sc3Ur4Uxpp

# Custom CSS
custom_css:
 - /assets/css/custom.css
